CERT.IDS00.TDSQL=true
CERT.IDS03.TDLOG=true
CERT.IDS04.TDFNAMES=true
CERT.IDS06.VAFS=true
CERT.IDS06.TDINPUT=true
CERT.IDS07.EXEC=true
CERT.IDS11.VPPD=true
CERT.IDS16.TDXML=true
CERT.IDS16.XMLVAL=true
CERT.DCL00.ACD=true
CERT.DCL02.ITMOD=true
CERT.EXP00.NASSIG=true
CERT.EXP00.AECB=true
CERT.EXP01.NP=true
CERT.EXP01.NCMD=true
CERT.EXP02.UEIC=true
CERT.EXP03.UEIC=true
CERT.EXP04.CMMT=true
CERT.EXP05.CID=true
CERT.EXP06.EASE=true
CERT.NUM00.ICO=true
CERT.NUM00.BSA=true
CERT.NUM00.CACO=true
CERT.NUM01.NCBAV=true
CERT.NUM01.BADSHIFT=true
CERT.NUM02.ZERO=true
CERT.NUM04.UBD=true
CERT.NUM07.NAN=true
CERT.NUM08.FPEXC=true
CERT.NUM09.FPLI=true
CERT.NUM10.BBDCC=true
CERT.NUM12.CLP=true
CERT.NUM13.AIC=true
CERT.STR00.COS=true
CERT.STR01.NCUCP=true
CERT.STR02.CCL=true
CERT.STR02.CTLC=true
CERT.OBJ03.AGBPT=true
CERT.OBJ04.CLONE=true
CERT.OBJ04.CPCL=true
CERT.OBJ04.MPT=true
CERT.OBJ04.SMO=true
CERT.OBJ04.MUCOP=true
CERT.OBJ05.CPCL=true
CERT.OBJ05.MPT=true
CERT.OBJ05.SMO=true
CERT.OBJ05.MUCOP=true
CERT.OBJ06.CPCL=true
CERT.OBJ06.MPT=true
CERT.OBJ06.SMO=true
CERT.OBJ06.MUCOP=true
CERT.OBJ07.MCNC=true
CERT.OBJ08.INNER=true
CERT.OBJ09.CMP=true
CERT.OBJ10.SPFF=true
CERT.OBJ10.RMO=true
CERT.OBJ11.EPNFC=true
CERT.OBJ13.RMO=true
CERT.MET02.DPRAPI=true
CERT.MET02.THRD=true
CERT.MET04.OPM=true
CERT.MET06.CLONE=true
CERT.MET07.AHSM=true
CERT.MET08.EQREFL=true
CERT.MET09.OVERRIDE=true
CERT.MET11.IKICO=true
CERT.MET12.MNDF=true
CERT.MET12.FCF=true
CERT.MET12.FM=true
CERT.MET12.IFF=true
CERT.MET12.NCF=true
CERT.MET12.OF=true
CERT.MET12.EF=true
CERT.MET12.FCSF=true
CERT.MET12.MFP=true
CERT.ERR00.LGE=true
CERT.ERR00.UCATCH=true
CERT.ERR01.ACPST=true
CERT.ERR01.CETS=true
CERT.ERR01.ACW=true
CERT.ERR01.EXCEPT=true
CERT.ERR02.SIO=true
CERT.ERR03.REVOBJ=true
CERT.ERR04.ARCF=true
CERT.ERR04.ATSF=true
CERT.ERR05.ARCF=true
CERT.ERR05.ATSF=true
CERT.ERR07.NTERR=true
CERT.ERR07.NTX=true
CERT.ERR08.NCNPE=true
CERT.ERR09.EXIT=true
CERT.ERR09.JVM=true
CERT.VNA00.LORD=true
CERT.VNA00.MRAV=true
CERT.VNA01.SGAS=true
CERT.VNA02.SSUG=true
CERT.VNA02.MRAV=true
CERT.VNA03.SSUG=true
CERT.VNA03.MRAV=true
CERT.LCK00.SOPF=true
CERT.LCK01.SCS=true
CERT.LCK02.SGC=true
CERT.LCK04.SOBC=true
CERT.LCK05.IASF=true
CERT.LCK06.INSTLOCK=true
CERT.LCK07.LORD=true
CERT.LCK08.RLF=true
CERT.LCK08.LOCK=true
CERT.LCK09.TSHL2=true
CERT.LCK09.TSHL=true
CERT.LCK10.DCL=true
CERT.THI00.IRUN=true
CERT.THI01.AUTG=true
CERT.THI02.ANF=true
CERT.THI03.UWIL=true
CERT.THI05.THRD=true
CERT.TPS00.ISTART=true
CERT.TSM00.OSNS=true
CERT.TSM01.CTRE=true
CERT.TSM02.CSTART=true
CERT.FIO01.CFAP=true
CERT.FIO01.ASNF=true
CERT.FIO02.NASSIGIO=true
CERT.FIO03.ATF=true
CERT.FIO03.REMTMP=true
CERT.FIO04.LEAKS=true
CERT.FIO04.CIO=true
CERT.FIO04.CCR=true
CERT.FIO05.BUFEXP=true
CERT.FIO06.MULBUF=true
CERT.FIO07.EXEC=true
CERT.FIO07.PBIOS=true
CERT.FIO08.CRRV=true
CERT.FIO09.ARGWRITE=true
CERT.FIO10.NASSIGIO=true
CERT.FIO12.PMRWLED=true
CERT.FIO13.SENS=true
CERT.FIO13.LHII=true
CERT.FIO13.PEO=true
CERT.FIO13.CONSEN=true
CERT.FIO14.CIO=true
CERT.FIO14.CCR=true
CERT.FIO14.CRWD=true
CERT.FIO16.CDBV=true
CERT.FIO16.CANPATH=true
CERT.SER00.DUID=true
CERT.SER01.ROWO=true
CERT.SER02.SSSD=true
CERT.SER03.SIF=true
CERT.SER04.SCSER=true
CERT.SER06.OROM=true
CERT.SER06.ZOIS=true
CERT.SER07.RRSC=true
CERT.SER09.VREADOBJ=true
CERT.SER11.IRX=true
CERT.SER12.VOBD=true
CERT.SEC01.PRIVIL=true
CERT.SEC02.TDRFL=true
CERT.SEC03.ACL=true
CERT.SEC04.SCF=true
CERT.SEC05.ARM=true
CERT.SEC06.SIGCLASS=true
CERT.SEC07.GETPERM=true
CERT.ENV02.ENV=true
CERT.JNI00.NATIW=true
CERT.JNI01.TDLIB=true
CERT.MSC00.USC=true
CERT.MSC01.EB=true
CERT.MSC02.SRD=true
CERT.MSC03.HCCS=true
CERT.MSC03.HCCK=true
CERT.MSC03.AHCA=true
CERT.MSC04.LEAKS=true
CERT.MSC06.ITMOD=true
CERT.MSC07.ILI=true
# Test configuration metadata

# Configuration parameters
com.parasoft.xtest.checkers.api.config.tool=1
configuration.name=CERT for Java
configuration.path=Compliance Packs/Security Pack
