PCIDSS40.6241.TDCMD=true
PCIDSS40.6241.TDALLOC=true
PCIDSS40.6241.UPS=true
PCIDSS40.6241.TDSQL=true
PCIDSS40.6241.TDLDAP=true
PCIDSS40.6241.TDNET=true
PCIDSS40.6241.TDRFL=true
PCIDSS40.6241.TDXPATH=true
PCIDSS40.6241.TDENV=true
PCIDSS40.6241.TDJXPATH=true
PCIDSS40.6241.TDLOG=true
PCIDSS40.6241.TDDIG=true
PCIDSS40.6241.TDXML=true
PCIDSS40.6241.XPIJ=true
PCIDSS40.6241.TDINPUT=true
PCIDSS40.6241.ARRAY=true
PCIDSS40.6241.AEAF=true
PCIDSS40.6241.AUXD=true
PCIDSS40.6241.DCEMSL=true
PCIDSS40.6241.TDFNAMES=true
PCIDSS40.6242.TDFNAMES=true
PCIDSS40.6242.MULBUF=true
PCIDSS40.6242.BUFEXP=true
PCIDSS40.6242.SIS=true
PCIDSS40.6242.INSTLOCK=true
PCIDSS40.6242.WCMT=true
PCIDSS40.6242.WCUTS=true
PCIDSS40.6242.TDNET=true
PCIDSS40.6242.TDINPUT=true
PCIDSS40.6242.TDALLOC=true
PCIDSS40.6242.ARRAY=true
PCIDSS40.6243.AISSAJAVA=true
PCIDSS40.6243.AISSAXML=true
PCIDSS40.6243.CKTS=true
PCIDSS40.6243.HCCK=true
PCIDSS40.6243.AUNC=true
PCIDSS40.6243.ICA=true
PCIDSS40.6243.MDSALT=true
PCIDSS40.6243.ACMD=true
PCIDSS40.6243.PLC=true
PCIDSS40.6243.PWDPROP=true
PCIDSS40.6243.PWDXML=true
PCIDSS40.6243.WCPWD=true
PCIDSS40.6243.WPWD=true
PCIDSS40.6243.SRD=true
PCIDSS40.6243.WCMC=true
PCIDSS40.6243.WCMI=true
PCIDSS40.6243.WCMWS=true
PCIDSS40.6244.TDRESP=true
PCIDSS40.6244.CDBV=true
PCIDSS40.6244.CHECKRET=true
PCIDSS40.6244.SENS=true
PCIDSS40.6244.TDXSS=true
PCIDSS40.6244.VPPD=true
PCIDSS40.6244.EACM=true
PCIDSS40.6244.ASAPI=true
PCIDSS40.6244.ZOIS=true
PCIDSS40.6244.SCHTTP=true
PCIDSS40.6244.DCSRFJAVA=true
PCIDSS40.6244.DCSRFXML=true
PCIDSS40.6245.TDPASSWD=true
PCIDSS40.6245.ISL=true
PCIDSS40.6245.RUIM=true
PCIDSS40.6245.HGRSI=true
PCIDSS40.6245.PTPT=true
PCIDSS40.6245.UTAX=true
PCIDSS40.6245.DNSL=true
PCIDSS40.6245.STTL=true
PCIDSS40.6245.UOSC=true
PCIDSS40.6245.PERMIT=true
PCIDSS40.6245.DSR=true
PCIDSS40.6245.SRCD=true
PCIDSS40.6245.CQRO=true
PCIDSS40.6245.UPWD=true
PCIDSS40.6245.PCCF=true
# Test configuration metadata

# Configuration parameters
com.parasoft.xtest.checkers.api.config.tool=1
configuration.name=PCI DSS 4.0
configuration.path=Compliance Packs/Security Pack
